import type { Metadata } from 'next'
import './globals.css'
import { Header } from '@/components/Header'
import { Footer } from '@/components/Footer'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="bg-[--brand-background] text-[--brand-white] antialiased">
        <Header />
        <main className="min-h-screen px-4 md:px-8 lg:px-16">{children}</main>
        <Footer />
      </body>
    </html>
  )
}